import { pgTable, pgEnum, uuid, text, timestamp, boolean, vector } from "drizzle-orm/pg-core";

// ─── Enums ──────────────────────────────────────────────────────
// PostgreSQL enums enforce allowed values at the DB level.
// If someone tries to insert type = "youtub" (typo), the DB rejects it.

export const contentTypeEnum = pgEnum("content_type", [
  "youtube",
  "twitter",
  "reddit",
  "github",
  "instagram",
  "article",
  "link",            // fallback for any URL we can't classify
]);

export const processingStatusEnum = pgEnum("processing_status", [
  "pending",         // just saved, no processing yet
  "processing",      // BullMQ worker picked it up
  "done",            // summary + tags + embedding all generated
  "failed",          // worker failed after retries
]);

// ─── Users ──────────────────────────────────────────────────────
// Equivalent to your old UserSchema.
// Key differences:
//   - id is UUID instead of MongoDB ObjectId
//   - timestamps are explicit columns (Mongoose hid them behind { timestamps: true })

export const users = pgTable("users", {
  id:        uuid("id").primaryKey().defaultRandom(),
  username:  text("username").notNull(),
  email:     text("email").notNull().unique(),
  password:  text("password").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// ─── Contents ───────────────────────────────────────────────────
// Equivalent to your old ContentSchema, but with new columns for
// the smart ingestion pipeline (Day 1-2) and semantic search (Day 3).
//
// Columns you already had:  title, link, type, userId
// New columns for Day 1:    ogTitle, ogDescription, ogImage, ogSiteName, embedUrl
// New columns for Day 2:    extractedText, summary, tags, processingStatus
// New columns for Day 3:    embedding (pgvector — added on Day 3, not here yet)
//
// We define ALL the columns now so you only run `drizzle-kit push` once.
// The columns are nullable where the data comes from async processing —
// they'll be NULL when the card is first created, then populated by BullMQ workers.

export const contents = pgTable("contents", {
  id:               uuid("id").primaryKey().defaultRandom(),

  // ── Core fields (what you already had) ──
  link:             text("link").notNull(),
  title:            text("title"),                                    // user-provided title, or auto-filled from OG tags
  type:             contentTypeEnum("type").notNull().default("link"),

  // ── Relationship ──
  // .references() creates a foreign key constraint.
  // onDelete: "cascade" means: if a user is deleted, all their content is deleted too.
  // In Mongoose, you had { type: ObjectId, ref: 'User' } but it wasn't enforced.
  userId:           uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),

  // ── OpenGraph metadata (Day 1 — fetched when URL is saved) ──
  ogTitle:          text("og_title"),
  ogDescription:    text("og_description"),
  ogImage:          text("og_image"),
  ogSiteName:       text("og_site_name"),
  favicon:          text("favicon"),

  // ── Embed data (Day 1 — for rendering rich cards) ──
  // embedUrl is the embeddable URL, different from the original link.
  // e.g., link = "youtube.com/watch?v=xxx" but embedUrl = "youtube.com/embed/xxx"
  embedUrl:         text("embed_url"),

  // ── Extracted content (Day 2 — populated by BullMQ worker) ──
  extractedText:    text("extracted_text"),          // article body, transcript, tweet text
  summary:          text("summary"),                 // Claude-generated summary

  // ── Tags (Day 2 — auto-generated by Claude) ──
  // PostgreSQL TEXT[] — a native array of strings.
  // In Mongoose you had: tags: [{ type: ObjectId, ref: 'Tag' }]
  // That referenced a separate Tag collection. Using a string array is simpler
  // and avoids an extra table + joins for what's really just a list of labels.
  tags:             text("tags").array().default([]),

  // ── Processing status (Day 2 — tracks BullMQ job progress) ──
  processingStatus: processingStatusEnum("processing_status").notNull().default("pending"),

  // ── Embedding (Day 3 — pgvector for semantic search) ──
  // 1536-dimensional vector from OpenAI text-embedding-3-small.
  // Stored as a native pgvector column — queried with cosine distance.
  embedding:        vector("embedding", { dimensions: 1536 }),

  // ── Timestamps ──
  createdAt:        timestamp("created_at").defaultNow().notNull(),
  updatedAt:        timestamp("updated_at").defaultNow().notNull(),
});

// ─── Share Links ────────────────────────────────────────────────
// Equivalent to your old LinksSchema.
// Lets users generate a public link to share their entire brain.

export const shareLinks = pgTable("share_links", {
  id:     uuid("id").primaryKey().defaultRandom(),
  hash:   text("hash").notNull().unique(),
  userId: uuid("user_id").notNull().unique().references(() => users.id, { onDelete: "cascade" }),
  // unique on userId means one share link per user (same as your Mongoose schema)
});

// ─── Type Exports ───────────────────────────────────────────────
// Drizzle can infer TypeScript types from your schema.
// These replace the Mongoose document types you used to get.

// InferSelectModel = the shape of a row when you SELECT from the table
// InferInsertModel = the shape of data when you INSERT (optional fields allowed)
import type { InferSelectModel, InferInsertModel } from "drizzle-orm";

export type User = InferSelectModel<typeof users>;
export type NewUser = InferInsertModel<typeof users>;

export type Content = InferSelectModel<typeof contents>;
export type NewContent = InferInsertModel<typeof contents>;

export type ShareLink = InferSelectModel<typeof shareLinks>;
export type NewShareLink = InferInsertModel<typeof shareLinks>;